# Generated by Django 6.1 on 2026-08-16 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='archivo_principal',
            field=models.FileField(blank=True, null=True, upload_to='contratos/principales/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='fecha_firma',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='tipo_contrato',
            field=models.CharField(choices=[('PRESTACION_SERVICIOS', 'Prestación de servicios'), ('SUMINISTRO', 'Suministro'), ('COMPRAVENTA', 'Compraventa'), ('ARRENDAMIENTO', 'Arrendamiento'), ('CONVENIO', 'Convenio'), ('OTRO', 'Otro')], default='OTRO', max_length=30),
        ),
        migrations.AlterField(
            model_name='documentocontrato',
            name='archivo',
            field=models.FileField(upload_to='contratos/documentos/%Y/%m/'),
        ),
    ]
