# Generated by Django 6.1 on 2026-08-13 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red_social', models.CharField(choices=[('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instagram'), ('TIKTOK', 'TikTok'), ('OTRA', 'Otra')], max_length=20)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('tema', models.CharField(max_length=150)),
                ('contenido', models.TextField()),
                ('tipo_contenido', models.CharField(blank=True, max_length=50)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PROGRAMADA', 'Programada'), ('PUBLICADA', 'Publicada')], default='BORRADOR', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publicaciones_creadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
