# Generated by Django 6.1 on 2026-08-18 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_radicado', models.CharField(max_length=50, unique=True)),
                ('tipo', models.CharField(choices=[('RECIBIDA', 'Recibida'), ('ENVIADA', 'Enviada')], max_length=10)),
                ('fecha', models.DateField()),
                ('remitente', models.CharField(max_length=200)),
                ('destinatario', models.CharField(max_length=200)),
                ('asunto', models.CharField(max_length=250)),
                ('descripcion', models.TextField(blank=True)),
                ('canal', models.CharField(choices=[('CORREO', 'Correo electrónico'), ('FISICO', 'Documento físico'), ('TELEFONO', 'Teléfono'), ('WHATSAPP', 'WhatsApp'), ('OTRO', 'Otro')], default='CORREO', max_length=20)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_TRAMITE', 'En trámite'), ('RESPONDIDA', 'Respondida'), ('CERRADA', 'Cerrada')], default='PENDIENTE', max_length=20)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='comunicaciones/%Y/%m/')),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comunicaciones_asignadas', to=settings.AUTH_USER_MODEL)),
                ('respuesta_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas', to='comunicaciones.comunicacion')),
            ],
        ),
    ]
