# Generated by Django 6.1 on 2026-08-19 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicaciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comunicacion',
            name='canal',
        ),
        migrations.RemoveField(
            model_name='comunicacion',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='comunicacion',
            name='destinatario',
        ),
        migrations.RemoveField(
            model_name='comunicacion',
            name='fecha',
        ),
        migrations.AddField(
            model_name='comunicacion',
            name='dependencia',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='comunicacion',
            name='enviado_a',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='comunicacion',
            name='estado_actual_texto',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='comunicacion',
            name='estado_inicial',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='comunicacion',
            name='fecha_asignacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comunicacion',
            name='fecha_recibido',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comunicacion',
            name='hora_asignacion',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comunicacion',
            name='hora_recibido',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comunicacion',
            name='item',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comunicacion',
            name='responsable_texto',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='comunicacion',
            name='termino_dias',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comunicacion',
            name='tipo',
            field=models.CharField(choices=[('RECIBIDA', 'Recibida'), ('ENVIADA', 'Enviada')], default='RECIBIDA', max_length=10),
        ),
    ]
