# Generated by Django 6.1 on 2026-08-19 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicaciones', '0002_remove_comunicacion_canal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunicacion',
            name='item',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
