# Generated by Django 6.1 on 2026-08-13 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_radicado', models.CharField(max_length=50, unique=True)),
                ('fecha_documento', models.DateField()),
                ('remitente', models.CharField(max_length=150)),
                ('asunto', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('INTERNO', 'Interno')], default='ENTRADA', max_length=20)),
                ('estado', models.CharField(choices=[('RECIBIDO', 'Recibido'), ('ASIGNADO', 'Asignado'), ('EN_TRAMITE', 'En trámite'), ('RESPONDIDO', 'Respondido'), ('ARCHIVADO', 'Archivado')], default='RECIBIDO', max_length=20)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='documentos/%Y/%m/')),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_asignados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
