# Generated by Django 6.1 on 2026-08-15 23:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documento',
            name='dependencia',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='documento',
            name='destinatario',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='documento',
            name='fecha_recepcion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
