# Generated by Django 6.1 on 2026-08-13 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publicaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricaPublicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alcance', models.PositiveIntegerField(default=0)),
                ('reacciones', models.PositiveIntegerField(default=0)),
                ('comentarios', models.PositiveIntegerField(default=0)),
                ('compartidos', models.PositiveIntegerField(default=0)),
                ('guardados', models.PositiveIntegerField(default=0)),
                ('impresiones', models.PositiveIntegerField(default=0)),
                ('fecha_medicion', models.DateTimeField(auto_now_add=True)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metricas', to='publicaciones.publicacion')),
            ],
        ),
    ]
